/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_deepblue_logd_DeepBlueNativeLog */

#ifndef _Included_com_deepblue_logd_DeepBlueNativeLog
#define _Included_com_deepblue_logd_DeepBlueNativeLog
#ifdef __cplusplus
extern "C" {
#endif

#include "clogan_core.h"
/*
 * Class:     com_deepblue_logd_DeepBlueNativeLog
 * Method:    native_init
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_deepblue_logd_DeepBlueNativeLog_native_1init
  (JNIEnv *env, jobject instance, jstring cache_path_, jstring dir_path_, jint max_file);

/*
 * Class:     com_deepblue_logd_DeepBlueNativeLog
 * Method:    native_open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_deepblue_logd_DeepBlueNativeLog_native_1open
  (JNIEnv *env, jobject instance, jstring file_name_);

/*
 * Class:     com_deepblue_logd_DeepBlueNativeLog
 * Method:    native_write
 * Signature: (ILjava/lang/String;JLjava/lang/String;JI)I
 */
JNIEXPORT jint JNICALL Java_com_deepblue_logd_DeepBlueNativeLog_native_1write
  (JNIEnv *env, jobject instance, jint flag, jstring log_, jlong local_time, jstring thread_name_, jlong thread_id, jint ismain);

/*
 * Class:     com_deepblue_logd_DeepBlueNativeLog
 * Method:    native_flush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_deepblue_logd_DeepBlueNativeLog_native_1flush
  (JNIEnv *env, jobject instance);

#ifdef __cplusplus
}
#endif
#endif
